// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserAPI.Context;

#nullable disable

namespace UserAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230512175352_Imigrantlar2")]
    partial class Imigrantlar2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UserAPI.Entites.Foydalanuvchi", b =>
                {
                    b.Property<string>("Ismi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Foydalanuvchi");
                });
#pragma warning restore 612, 618
        }
    }
}
